import React from 'react';

export default function Contract(props) {

	return (
		<div className="contract">
			<p>
				MPK BASEBALL AND SOFTBALL, INC.<br/>
				RELEASE AND WAIVER OF LIABILITY, <br/>
				ASSUMPTION OF RISK, <br/>
				AND INDEMNITY AGREEMENT
			</p>
			<p>IN CONSIDERATION of my child being allowed to participate in activities and events offered and/or sponsored by MPK Baseball and Softball, Inc., including the activities and events of the various teams within MPK Baseball and Softball, Inc., through December 31 of the current year, and on behalf of myself, my participating child, and my personal representatives, heirs, children, and successors and assigns, I agree as follows: 
			</p>
			<ol>
				<li>I HEREBY GENERALLY AND SPECIFICALLY RELEASE, WAIVE, DISCHARGE, AND COVENANT NOT TO SUE MPK Baseball and Softball, Inc. or any of its affiliates, directors, officers, members, shareholders, employees, representatives, contractors, agents, officials, committee members, teams, managers, coaches, players, participants, facility owners and lessees, sponsors, advertisers, donors, volunteers, guests, invitees, predecessors and successors in interest, assigns, and all persons assisting in the conduct of MPK Baseball and Softball, Inc. activities or events (MPK Baseball and Softball, Inc. and the foregoing persons, individuals, entities, and third parties shall each hereinafter be referred to as a “RELEASEE” or collectively the “RELEASEES”), FROM ANY AND ALL PAST, PRESENT OR FUTURE CLAIMS, DEMANDS, LIABILITIES, ACTIONS, CAUSES OF ACTION, SUITS, JUDGMENTS, ORDERS, HEARINGS, PROCEEDINGS, LOSSES, DAMAGES, COSTS, EXPENSES, OBLIGATIONS, INCLUDING, WITHOUT LIMITATION, ATTORNEYS’ FEES AND ANY AND ALL FEES OR COSTS OF EVERY NATURE, CHARACTER OR DESCRIPTION WHATSOEVER (the foregoing shall each hereinafter be referred to as a “Claim” or collectively as the “Claims”), ARISING OUT OF, RELATED TO, IN CONNECTION WITH, OR ON ACCOUNT OF ANY MPK BASEBALL AND SOFTBALL, INC. EVENT OR OTHER ACTIVITY, including, without limitation, any Claim involving personal injury (including death) or property damage; and from any cause whatsoever, including, without limitation, the failure of anyone to enforce rules and regulations, to make inspections, the condition of any portion of the field, facilities, or premises, defective products, any act or omission of the RELEASEES, or any other act WHETHER CAUSED BY THE NEGLIGENCE OF THE RELEASEES OR OTHERWISE. This release, waiver, discharge, and covenant not to sue also expressly covers all Claims arising from or in any way related to my presence, attendance, or participation, or the presence, attendance, or participation of my child, for any reason whatsoever at the facilities of or used by MPK Baseball and Softball, Inc. or any Releasee, or on the premises where MPK Baseball and Softball, Inc. events and/or activities take place, including, without limitation, my involvement as a spectator, or my child’s involvement as a player or participant, and such release and waiver is extended to include all transportation to and from all activities and events. This release, waiver, discharge, and covenant not to sue also expressly covers all Claims against any RELEASEE for personal injuries (including death) or property damage sustained as a result of NEGLIGENT RESCUE OPERATIONS OR PROCEDURES.</li>
				<li>I HEREBY AGREE TO INDEMNIFY AND SAVE AND HOLD HARMLESS THE RELEASEES and each of them from any and all Claims they or any of them may incur or sustain arising from, related to, in connection with, or on account of any injury to or death of any person or damage to property, caused or alleged to be caused in whole or in part by the negligence of RELEASEES or otherwise, arising from or related in any way to any MPK Baseball and Softball, Inc. event or activity.  If despite the release set forth herein, I, my child, or anyone acting on my behalf or on behalf of my child, makes a Claim against any of the RELEASEES, I agree to indemnify, save and hold harmless, and defend, at my sole cost and expense, the RELEASEES, and each of them, from any and all such Claims that may be brought or instituted against the RELEASEES, whether the Claim is based on the negligence of the RELEASEES or otherwise arising from or related in any way to any MPK Baseball and Softball, Inc. event or activity.  My obligation to indemnify shall survive my participation and my child’s participation in MPK Baseball and Softball, Inc. events or activities for the full period of time allowed by law.  I further agree to pay and satisfy any judgment, award or decree that may be rendered against MPK Baseball and Softball, Inc. or any RELEASEE in connection with my participation or my child’s participation in MPK Baseball and Softball, Inc. events or activities.  I further agree to reimburse MPK Baseball and Softball, Inc. and any RELEASEE any and all legal expenses and costs incurred by each of them in connection therewith or in enforcing the indemnity herein provided.</li>
				<li>I HEREBY AGREE THAT THIS RELEASE AND WAIVER OF LIABILITY, ASSUMPTION OF RISK AND INDEMNITY AGREEMENT extends to all acts of negligence by the RELEASEES and is intended to be as broad and inclusive as is permitted by the laws of the State of California, and that if any portion of this agreement is held to be invalid or overly broad, the entire agreement will not be invalidated; rather, the agreement will be deemed modified so as to be applied to the fullest extent permitted by applicable law.</li>

				<li>I HEREBY ACKOWLEDGE, agree, and represent that I understand the nature of baseball and softball activities, and that my child and I are qualified, are in good health, and in proper physical condition to participate in such activities.  I further agree and warrant that if at any time my child and/or I believe conditions to be unsafe, my child and/or I will immediately discontinue further participation in the activities.
				</li>
				<li>I HEREBY FULLY UNDERSTAND THAT: (a) baseball and softball activities involve risks and dangers of serious bodily injury, including permanent disability, paralysis, and death; (b) these risks and dangers may be caused by my own actions or inactions, the actions or inactions of my child, the actions or inactions of others participating in the activities, the condition in which the activity takes place, or the negligence of the RELEASEES listed above; and (c) there may be other risks and social and economic losses either not known to me or not readily foreseeable at this time, and I, on behalf of myself and that of my participating child, FULLY ACCEPT AND ASSUME ALL SUCH RISKS AND ALL RESPONSIBILITY FOR LOSSES, COSTS, AND DAMAGES, I incur, or my child incurs, as a result of my participation or the participation of my child arising out of or related to any MPK Baseball and Softball, Inc. event or other activity.</li>
				<li>I sign this RELEASE AND WAIVER OF LIABILITY, ASSUMPTION OF RISK AND INDEMNITY AGREEMENT on my own behalf and on behalf of my child. By my signature below, I warrant that I am the parent or legal guardian of the participating child as designated on the corresponding League Application and Parents’ Contract, and that I am legally authorized to sign this agreement on behalf of the participating child. </li>
					<li>THIS RELEASE AND WAIVER OF LIABILITY, ASSUMPTION OF RISK AND INDEMNITY AGREEMENT shall be binding as to my child, whether signed by one parent or both parents, and shall also be binding as to each signing parent.</li>
					<li>I HAVE READ THIS RELEASE AND WAIVER OF LIABILITY, ASSUMPTION OF RISK AND INDEMNITY AGREEMENT, FULLY UNDERSTAND ITS TERMS, UNDERSTAND THAT I HAVE GIVEN UP SUBSTANTIAL RIGHTS BY SIGNING IT, INCLUDING THE RIGHTS OF MY PARTICIPATING CHILD, AND I HAVE SIGNED IT FREELY AND VOLUNTARILY WITHOUT ANY INDUCEMENT, ASSURANCE, OR GUARANTEE BEING MADE TO ME, AND I INTEND MY SIGNATURE TO BE A COMPLETE AND UNCONDITIONAL RELEASE OF LIABILITY TO THE GREATEST EXTENT ALLOWED BY LAW. I further agree that no oral representations, statements or inducements, apart from the foregoing written agreement, have been made. 
				</li>
		</ol>
		</div>
	);
}